services:
  role-bot:
    image: discord-role-icon-bot:latest
    container_name: role-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./configuration.json:/root/.config/role-icon-bot/configuration.json
    network_mode: host
